





import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class department_detail07 extends javax.swing.JFrame {

    /**
     * Creates new form department_detail
     */
    public department_detail07() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        dicriptionbutton07 = new javax.swing.JButton();
        menberbutton07 = new javax.swing.JButton();
        reportbutton07 = new javax.swing.JButton();
        agendabutton07 = new javax.swing.JButton();
        detaiexit = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dicriptionbutton07.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        dicriptionbutton07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/discription_1.png"))); // NOI18N
        dicriptionbutton07.setText("ገለጻ");
        dicriptionbutton07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dicriptionbutton07ActionPerformed(evt);
            }
        });

        menberbutton07.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        menberbutton07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-members-64.png"))); // NOI18N
        menberbutton07.setText("አባላት");
        menberbutton07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menberbutton07ActionPerformed(evt);
            }
        });

        reportbutton07.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        reportbutton07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/report_department.png"))); // NOI18N
        reportbutton07.setText("ሪፖርት");
        reportbutton07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportbutton07ActionPerformed(evt);
            }
        });

        agendabutton07.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        agendabutton07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-agenda-64.png"))); // NOI18N
        agendabutton07.setText("አጀንዳ");
        agendabutton07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendabutton07ActionPerformed(evt);
            }
        });

        detaiexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        detaiexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        detaiexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detaiexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(detaiexit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(dicriptionbutton07)
                .addGap(226, 226, 226)
                .addComponent(menberbutton07)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addComponent(reportbutton07)
                .addGap(318, 318, 318)
                .addComponent(agendabutton07)
                .addGap(165, 165, 165))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dicriptionbutton07)
                            .addComponent(menberbutton07)
                            .addComponent(reportbutton07)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(agendabutton07)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 564, Short.MAX_VALUE)
                .addComponent(detaiexit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dicriptionbutton07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dicriptionbutton07ActionPerformed
              new muyaenateradio().setVisible(true);
// TODO add your handling code here:
             
             
             
    }//GEN-LAST:event_dicriptionbutton07ActionPerformed

    private void detaiexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detaiexitActionPerformed
                          setVisible(false);
                          new homepage().setVisible(true);
                          new departments().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_detaiexitActionPerformed

    private void menberbutton07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menberbutton07ActionPerformed
        // TODO add your handling code here
        new regstration07().setVisible(true);
        detaiexit.setVisible(true);
        
    }//GEN-LAST:event_menberbutton07ActionPerformed

    private void agendabutton07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendabutton07ActionPerformed
        // TODO add your handling code here:
        new Agenda7().setVisible(true);
    }//GEN-LAST:event_agendabutton07ActionPerformed

    private void reportbutton07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportbutton07ActionPerformed
        new report07().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_reportbutton07ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(department_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(department_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(department_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(department_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new department_detail07().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendabutton07;
    private javax.swing.JButton detaiexit;
    private javax.swing.JButton dicriptionbutton07;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JButton menberbutton07;
    private javax.swing.JButton reportbutton07;
    // End of variables declaration//GEN-END:variables
}
