





import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class department_detail06 extends javax.swing.JFrame {

    /**
     * Creates new form department_detail
     */
    public department_detail06() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        dicriptionbutton06 = new javax.swing.JButton();
        menberbutton06 = new javax.swing.JButton();
        reportbutton06 = new javax.swing.JButton();
        agendabutton06 = new javax.swing.JButton();
        detaiexit = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dicriptionbutton06.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        dicriptionbutton06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/discription_1.png"))); // NOI18N
        dicriptionbutton06.setText("ገለጻ");
        dicriptionbutton06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dicriptionbutton06ActionPerformed(evt);
            }
        });

        menberbutton06.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        menberbutton06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-members-64.png"))); // NOI18N
        menberbutton06.setText("አባላት");
        menberbutton06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menberbutton06ActionPerformed(evt);
            }
        });

        reportbutton06.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        reportbutton06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/report_department.png"))); // NOI18N
        reportbutton06.setText("ሪፖርት");
        reportbutton06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportbutton06ActionPerformed(evt);
            }
        });

        agendabutton06.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        agendabutton06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-agenda-64.png"))); // NOI18N
        agendabutton06.setText("አጀንዳ");
        agendabutton06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendabutton06ActionPerformed(evt);
            }
        });

        detaiexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        detaiexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        detaiexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detaiexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(detaiexit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(dicriptionbutton06)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                .addComponent(menberbutton06)
                .addGap(245, 245, 245)
                .addComponent(reportbutton06)
                .addGap(300, 300, 300)
                .addComponent(agendabutton06)
                .addGap(131, 131, 131))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dicriptionbutton06)
                    .addComponent(agendabutton06)
                    .addComponent(reportbutton06)
                    .addComponent(menberbutton06))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 570, Short.MAX_VALUE)
                .addComponent(detaiexit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dicriptionbutton06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dicriptionbutton06ActionPerformed
              // TODO add your handling code here:
              new mezmurkfl().setVisible(true);
            
             
    }//GEN-LAST:event_dicriptionbutton06ActionPerformed

    private void detaiexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detaiexitActionPerformed
                          setVisible(false);
                          new homepage().setVisible(true);
                          new departments().setVisible(true);
                          
// TODO add your handling code here:
    }//GEN-LAST:event_detaiexitActionPerformed

    private void menberbutton06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menberbutton06ActionPerformed
        // TODO add your handling code here
        new regstration06().setVisible(true);
        detaiexit.setVisible(true);
        
    }//GEN-LAST:event_menberbutton06ActionPerformed

    private void reportbutton06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportbutton06ActionPerformed
        new report06().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_reportbutton06ActionPerformed

    private void agendabutton06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendabutton06ActionPerformed
        new Agenda6().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_agendabutton06ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(department_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(department_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(department_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(department_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new department_detail06().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendabutton06;
    private javax.swing.JButton detaiexit;
    private javax.swing.JButton dicriptionbutton06;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JButton menberbutton06;
    private javax.swing.JButton reportbutton06;
    // End of variables declaration//GEN-END:variables
}
