





import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class department_detail03 extends javax.swing.JFrame {

    /**
     * Creates new form department_detail
     */
    public department_detail03() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        dicriptionbutton03 = new javax.swing.JButton();
        menberbutton03 = new javax.swing.JButton();
        reportbutton03 = new javax.swing.JButton();
        agendabutton03 = new javax.swing.JButton();
        detaiexit = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dicriptionbutton03.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        dicriptionbutton03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/discription_1.png"))); // NOI18N
        dicriptionbutton03.setText("ገለጻ");
        dicriptionbutton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dicriptionbutton03ActionPerformed(evt);
            }
        });

        menberbutton03.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        menberbutton03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-members-64.png"))); // NOI18N
        menberbutton03.setText("አባላት");
        menberbutton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menberbutton03ActionPerformed(evt);
            }
        });

        reportbutton03.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        reportbutton03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/report_department.png"))); // NOI18N
        reportbutton03.setText("ሪፖርት");
        reportbutton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportbutton03ActionPerformed(evt);
            }
        });

        agendabutton03.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        agendabutton03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-agenda-64.png"))); // NOI18N
        agendabutton03.setText("አጀንዳ");
        agendabutton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendabutton03ActionPerformed(evt);
            }
        });

        detaiexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        detaiexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        detaiexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detaiexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(detaiexit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(dicriptionbutton03)
                .addGap(206, 206, 206)
                .addComponent(menberbutton03)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(reportbutton03)
                .addGap(281, 281, 281)
                .addComponent(agendabutton03)
                .addGap(204, 204, 204))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dicriptionbutton03)
                    .addComponent(menberbutton03)
                    .addComponent(agendabutton03)
                    .addComponent(reportbutton03))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 570, Short.MAX_VALUE)
                .addComponent(detaiexit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dicriptionbutton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dicriptionbutton03ActionPerformed
              // TODO add your handling code here:
             new limat().setVisible(true);
             
    }//GEN-LAST:event_dicriptionbutton03ActionPerformed

    private void detaiexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detaiexitActionPerformed
                          setVisible(false);
                          new homepage().setVisible(true);
                          new departments().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_detaiexitActionPerformed

    private void menberbutton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menberbutton03ActionPerformed
        // TODO add your handling code here
        new regstration03().setVisible(true);
        //detaiexit.setVisible(true);
        
    }//GEN-LAST:event_menberbutton03ActionPerformed

    private void reportbutton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportbutton03ActionPerformed
        // TODO add your handling code here:
        new report03().setVisible(true);
    }//GEN-LAST:event_reportbutton03ActionPerformed

    private void agendabutton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendabutton03ActionPerformed
        // TODO add your handling code here:
        new Agenda3().setVisible(true);
    }//GEN-LAST:event_agendabutton03ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(department_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(department_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(department_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(department_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new department_detail03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendabutton03;
    private javax.swing.JButton detaiexit;
    private javax.swing.JButton dicriptionbutton03;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JButton menberbutton03;
    private javax.swing.JButton reportbutton03;
    // End of variables declaration//GEN-END:variables
}
