/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class regstration02 extends javax.swing.JFrame {

    /**
     * Creates new form regstration
     */
    private Connection connection;
    private String targetBatch;
    private String Department = "02";
    private int id;
    public regstration02() {
        initComponents();
         setExtendedState(JFrame.MAXIMIZED_BOTH);
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             connection = DriverManager.getConnection("jdbc:mysql://localhost/gbigubae", "root", "6789");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(regstration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
           
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        searchButton01 = new javax.swing.JButton();
        deleteButton01 = new javax.swing.JButton();
        menberupdateButton01 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setBackground(new java.awt.Color(34, 102, 141));
        kGradientPanel1.setkEndColor(new java.awt.Color(48, 77, 48));
        kGradientPanel1.setkStartColor(new java.awt.Color(48, 77, 48));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchButton01.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        searchButton01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        searchButton01.setText("ፈልግ");
        searchButton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton01ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(searchButton01, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 700, -1, -1));

        deleteButton01.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        deleteButton01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        deleteButton01.setText("አጥፋ");
        deleteButton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton01ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(deleteButton01, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 700, -1, -1));

        menberupdateButton01.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        menberupdateButton01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update.png"))); // NOI18N
        menberupdateButton01.setText("አሻሽል");
        menberupdateButton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menberupdateButton01ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(menberupdateButton01, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 699, -1, 60));

        jPanel1.setBackground(new java.awt.Color(238, 240, 229));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 102, 0), new java.awt.Color(255, 0, 204), new java.awt.Color(0, 255, 153,80), new java.awt.Color(153, 153, 0)));
        jPanel1.setForeground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 24)); // NOI18N
        jLabel1.setText("የ አባላት መመዝገቢያ ቅጽ");

        jLabel2.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        jLabel2.setText("ሙሉ ስም");

        jTextField1.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        jLabel3.setText("የ ኪርስትና ስም");

        jLabel4.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        jLabel4.setText("ትምህርት ክፍል");

        jLabel5.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        jLabel5.setText("ሴክሽን");

        jLabel6.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        jLabel6.setText("ባች");

        jLabel7.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        jLabel7.setText("ጾታ");

        jLabel8.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        jLabel8.setText("ክፍላት");

        jLabel9.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 18)); // NOI18N
        jLabel9.setText("ስልክ ቁጥር");

        jTextField2.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 12)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hydraulic and Water Resources  Engineering", "Water Resources and Irrigation  Engineering", "Water Supply and Environmental  Engineering", "Civil Engineering", "Electrical and Computer Engineering", "Software Engineering", "Mechanical Engineering", "Architecture and Urban Planning", "Information Technology", "Computer Science", "Survey Engineering" }));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "13", "14", "15", "16" }));

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setText("male");

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setText("female");

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11" }));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                            .addComponent(jTextField2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 319, Short.MAX_VALUE)
                            .addComponent(jTextField3)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(58, 58, 58)
                                .addComponent(jRadioButton2))
                            .addComponent(jComboBox3, 0, 319, Short.MAX_VALUE)
                            .addComponent(jTextField4))))
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jButton1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 590, 720));

        jTable1.setBackground(new java.awt.Color(204, 255, 255));
        jTable1.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "fullname", "crstianity name", "departments", "gender", "phone number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 190, 630, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "13", "14", "15", "16" }));
        kGradientPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 130, 80, -1));

        jLabel10.setFont(new java.awt.Font("A0 Tesfa Unicode", 1, 14)); // NOI18N
        jLabel10.setText("ባች ይምረጡ");
        kGradientPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, 120, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        jButton2.setText("finish");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 710, 100, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        
         
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            String fullName = jTextField1.getText();
    String christianityName = jTextField2.getText();
    String department = jComboBox1.getSelectedItem().toString();
    String section = jTextField3.getText();
    String batch = jComboBox2.getSelectedItem().toString();
    String gender = jRadioButton1.isSelected() ? "Male" : "Female";
    String departmentCode = jComboBox3.getSelectedItem().toString();
    String phoneNumber = jTextField4.getText();

    // JDBC Connection parameters
    //String url = "jdbc:mysql://localhost:3306/gbigubae";
    //String username = "root";
    //String password = "6789";

    try {
        // Establish the database connection
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/gbigubae","root","6789");

        // Prepare the SQL statement
       String sql = "INSERT INTO `members` (`fullname`, `crstianityname`, `acadamical department`, `section`, `batch`, `gender`, `department`, `phonenumber`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

        try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
            // Set parameters in the SQL statement
            preparedStatement.setString(1, fullName);
            preparedStatement.setString(2, christianityName);
            preparedStatement.setString(3, department);
            preparedStatement.setString(4, section);
            preparedStatement.setString(5, batch);
            preparedStatement.setString(6, gender);
            preparedStatement.setString(7, departmentCode);
            preparedStatement.setString(8, phoneNumber);

            // Execute the SQL statement
            preparedStatement.executeUpdate();
        }

        // Close the connection
        connection.close();

        // Display a success message or perform other actions
        JOptionPane.showMessageDialog(this, "Registration successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
        jTextField1.setText(""); // Full Name
        jTextField2.setText(""); // Christianity Name
        jComboBox1.setSelectedIndex(0); // Academic Department
        jTextField3.setText(""); // Section
        jComboBox2.setSelectedIndex(0); // Batch
        jRadioButton1.setSelected(true); // Set default gender to male
        jComboBox3.setSelectedIndex(0); // Department Code
        jTextField4.setText(""); // Phone Number
       
    } catch (SQLException e) {
        // Handle any SQL errors
        e.printStackTrace();
    }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(regstration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new department_detail02().setVisible(true);
        //new member().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchButton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton01ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn;
            conn = DriverManager.getConnection("jdbc:mysql://localhost/gbigubae", "root", "6789");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(regstration.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            String targetDepartment = "02";
             targetBatch = jComboBox4.getSelectedItem().toString();

            String sql = "SELECT fullname, crstianityname,`acadamical department`, gender, phonenumber,member_id FROM members WHERE batch = ? AND department = ?";
            try (PreparedStatement pst = connection.prepareStatement(sql)) {
                pst.setString(1, targetBatch);
                pst.setString(2, targetDepartment);

                try (ResultSet rs = pst.executeQuery()) {
                    if (!rs.isBeforeFirst()) {
                        JOptionPane.showMessageDialog(this, "No members avilable for selected batch.", "No Data", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        while (rs.next()) {
                            int idd=rs.getInt("member_id");
                            String name = rs.getString("fullname");
                            String c_name = rs.getString("crstianityname");
                            String dept = rs.getString("acadamical department");
                            String gender = rs.getString("gender");
                            String phone = rs.getString("phonenumber");

                            String tabledata[] = {String.valueOf(idd),name, c_name, dept, gender, phone};
                            DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
                            tb.setRowCount(0);
                            tb.addRow(tabledata);
                        }
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(regstration.class.getName()).log(Level.SEVERE, null, ex);
        }
    
                     
    }//GEN-LAST:event_searchButton01ActionPerformed

    private void menberupdateButton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menberupdateButton01ActionPerformed
        // TODO add your handling code here:
//        int selectedRow = jTable1.getSelectedRow();
//    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//    
//
//    jTextField1.setText(model.getValueAt(selectedRow, 1).toString()); // Full Name
//    jTextField2.setText(model.getValueAt(selectedRow, 2).toString()); // Christianity Name
//    jComboBox1.setSelectedItem(model.getValueAt(selectedRow, 3)); // Academic Department
//    jTextField3.setText(""); // Section
//    jComboBox2.setSelectedItem(targetBatch); // Batch
//    String gender = model.getValueAt(selectedRow, 4).toString();
//    if (gender.equals("Male")) {
//        jRadioButton1.setSelected(true);
//        jRadioButton2.setSelected(false);
//    } else {
//        jRadioButton1.setSelected(false);
//        jRadioButton2.setSelected(true);
//    }
//    jComboBox3.setSelectedIndex(10); // Department Code
//    jTextField4.setText(model.getValueAt(selectedRow, 5).toString()); // Phone Number
//    id = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());

        try {

            String updateQuery = "UPDATE members SET fullname=?, crstianityname=?, `acadamical department`=?, section=?, batch=?, gender=?, department=?, phonenumber=? WHERE member_id=?";
            try (PreparedStatement updateStatement = connection.prepareStatement(updateQuery)) {
                updateStatement.setString(1,jTextField1.getText() );
                updateStatement.setString(2, jTextField2.getText());
                updateStatement.setString(3, jComboBox1.getSelectedItem().toString());
                updateStatement.setString(4, jTextField3.getText());
                updateStatement.setString(5, jComboBox2.getSelectedItem().toString());
                updateStatement.setString(6, jRadioButton1.isSelected() ? "Male" : "Female");
                updateStatement.setString(7, jComboBox3.getSelectedItem().toString());
                updateStatement.setString(8, jTextField4.getText());
                // Set other parameters accordingly...
                updateStatement.setInt(9,id ); // Set the ID in the WHERE clause
                // Execute the update query
                
                updateStatement.executeUpdate();
                System.out.println("update completed");

                JOptionPane.showMessageDialog(this, "members data updated  successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
                // Update the JTable
                // Assuming dept is in the fourth column
                // Update other columns accordingly
                
                // Clear the text fields or reset them as needed
                
                jTextField1.setText(""); // Full Name
                jTextField2.setText(""); // Christianity Name
                jComboBox1.setSelectedIndex(0); // Academic Department
                jTextField3.setText(""); // Section
                jComboBox2.setSelectedIndex(0); // Batch
                jRadioButton1.setSelected(true); // Set default gender to male
                jComboBox3.setSelectedIndex(0); // Department Code
                jTextField4.setText(""); // Phone Number
                // Reset other fields...
//                int selectedRow = jTable1.getSelectedRow();
//DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//model.setValueAt(id, selectedRow, 0); // Assuming name is in the second column
//model.setValueAt(jTextField1.getText(), selectedRow, 1); // Assuming cName is in the third column
//model.setValueAt(jTextField2.getText(), selectedRow, 2);
//model.setValueAt(jComboBox1.getSelectedItem().toString(), selectedRow, 3);
//model.setValueAt(jRadioButton1.isSelected() ? "Male" : "Female", selectedRow, 4);
//model.setValueAt(jTextField4.getText(), selectedRow, 5);
//                // Close the statement
try {
    DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
          tb.setRowCount(0); // Clear existing rows
            String targetDepartment = "02";
             targetBatch = jComboBox4.getSelectedItem().toString();

            String sql = "SELECT fullname, crstianityname,`acadamical department`, gender, phonenumber,member_id FROM members WHERE batch = ? AND department = ?";
            try (PreparedStatement pst = connection.prepareStatement(sql)) {
                pst.setString(1, targetBatch);
                pst.setString(2, targetDepartment);

                try (ResultSet rs = pst.executeQuery()) {
                    if (!rs.isBeforeFirst()) {
                        JOptionPane.showMessageDialog(this, "No members avilable for selected batch.", "No Data", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        while (rs.next()) {
                            int id=rs.getInt("member_id");
                            String name = rs.getString("fullname");
                            String c_name = rs.getString("crstianityname");
                            String dept = rs.getString("acadamical department");
                            String gender = rs.getString("gender");
                            String phone = rs.getString("phonenumber");

                            String tabledata[] = {String.valueOf(id),name, c_name, dept, gender, phone};
                            
                            tb.addRow(tabledata);
                        }
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(regstration.class.getName()).log(Level.SEVERE, null, ex);
        }
            }

    } catch (SQLException ex) {
        // Handle exceptions appropriately
        ex.printStackTrace();
    }

        
    }//GEN-LAST:event_menberupdateButton01ActionPerformed

    @SuppressWarnings("empty-statement")
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    

    jTextField1.setText(model.getValueAt(selectedRow, 1).toString()); // Full Name
    jTextField2.setText(model.getValueAt(selectedRow, 2).toString()); // Christianity Name
    jComboBox1.setSelectedItem(model.getValueAt(selectedRow, 3)); // Academic Department
    jTextField3.setText(""); // Section
    jComboBox2.setSelectedItem(targetBatch); // Batch
    String gender = model.getValueAt(selectedRow, 4).toString();
    if (gender.equals("Male")) {
        jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
    } else {
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(true);
    }
    //*******************************************************************************************
    jComboBox3.setSelectedIndex(1); // Department Code
    jTextField4.setText(model.getValueAt(selectedRow, 5).toString()); // Phone Number
    id = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void deleteButton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton01ActionPerformed
        // TODO add your handling code here:
        
        try {
            int row = jTable1.getSelectedRow();
    String id = jTable1.getValueAt(row, 0).toString();
    String sql = "DELETE FROM members WHERE member_id=?";
            PreparedStatement stmt = connection.prepareStatement(sql);
    stmt.setString(1, id);
    stmt.executeUpdate();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.removeRow(row); // Remove the selected row from the table
            JOptionPane.showMessageDialog(this, "Student Deleted sucesfully");
            jTextField1.setText(""); // Full Name
                jTextField2.setText(""); // Christianity Name
                jComboBox1.setSelectedIndex(0); // Academic Department
                jTextField3.setText(""); // Section
                jComboBox2.setSelectedIndex(0); // Batch
                jRadioButton1.setSelected(true); // Set default gender to male
                jComboBox3.setSelectedIndex(0); // Department Code
                jTextField4.setText(""); // Phone Number
                
                try {
    //DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
//tb.setRowCount(0); // Clear existing rows
            String targetDepartment = "02";
             targetBatch = jComboBox4.getSelectedItem().toString();

            String sqll = "SELECT fullname, crstianityname,`acadamical department`, gender, phonenumber,member_id FROM members WHERE batch = ? AND department = ?";
            try (PreparedStatement pst = connection.prepareStatement(sqll)) {
                pst.setString(1, targetBatch);
                pst.setString(2, targetDepartment);

                try (ResultSet rs = pst.executeQuery()) {
                    if (!rs.isBeforeFirst()) {
                        JOptionPane.showMessageDialog(this, "No members avilable for selected batch.", "No Data", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        while (rs.next()) {
                            int idd=rs.getInt("member_id");
                            String name = rs.getString("fullname");
                            String c_name = rs.getString("crstianityname");
                            String dept = rs.getString("acadamical department");
                            String gender = rs.getString("gender");
                            String phone = rs.getString("phonenumber");

                            String tabledata[] = {String.valueOf(idd),name, c_name, dept, gender, phone};
                            DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
                            tb.addRow(tabledata);
                        }
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(regstration.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            //stmt.close();
        } catch (Exception e) {
            System.out.println("Error deleting from file");
        }

    }//GEN-LAST:event_deleteButton01ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regstration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regstration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regstration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regstration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regstration02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton01;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JButton menberupdateButton01;
    private javax.swing.JButton searchButton01;
    // End of variables declaration//GEN-END:variables
}
